default:
  image: ubuntu:focal

variables:
  GIT_DEPTH: 1
  DEBIAN_FRONTEND: 'noninteractive'
  TZ: UTC

# Define Stages
stages:
  - build

build-amd64:
  tags: [docker, multiarch]
  stage: build
  image:
    name: ghcr.io/claytonsingh/ubuntu-golang:amd64
    docker:
      platform: linux/amd64
  script:
    - flags="-X 'main.versionString=$(git show -s --format=%cs) ${CI_COMMIT_TAG} $(git rev-parse HEAD)'"
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o bin/icmp-exporter-amd64 -ldflags="${flags}" ./cmd/icmp-exporter/
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-i386:
  tags: [docker, multiarch]
  stage: build
  image:
    name: ghcr.io/claytonsingh/ubuntu-golang:i386
    docker:
      platform: linux/386
  script:
    - flags="-X 'main.versionString=$(git show -s --format=%cs) ${CI_COMMIT_TAG} $(git rev-parse HEAD)'"
    - CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -o bin/icmp-exporter-i386 -ldflags="${flags}" ./cmd/icmp-exporter/
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-arm64:
  tags: [docker, multiarch]
  stage: build
  image:
    name: ghcr.io/claytonsingh/ubuntu-golang:arm64
    docker:
      platform: linux/arm64
  script:
    - flags="-X 'main.versionString=$(git show -s --format=%cs) ${CI_COMMIT_TAG} $(git rev-parse HEAD)'"
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o bin/icmp-exporter-arm64 -ldflags="${flags}" ./cmd/icmp-exporter/
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-arm32v6:
  tags: [docker, multiarch]
  stage: build
  image:
    name: ghcr.io/claytonsingh/ubuntu-golang:armv5
    docker:
      platform: linux/arm/v6
  script:
    - flags="-X 'main.versionString=$(git show -s --format=%cs) ${CI_COMMIT_TAG} $(git rev-parse HEAD)'"
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -o bin/icmp-exporter-arm32v6 -ldflags="${flags}" ./cmd/icmp-exporter/
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-arm32v7:
  tags: [docker, multiarch]
  stage: build
  image:
    name: ghcr.io/claytonsingh/ubuntu-golang:armv7
    docker:
      platform: linux/arm/v7
  script:
    - flags="-X 'main.versionString=$(git show -s --format=%cs) ${CI_COMMIT_TAG} $(git rev-parse HEAD)'"
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm go build -o bin/icmp-exporter-arm32v7 -ldflags="${flags}" ./cmd/icmp-exporter/
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-riscv64:
  tags: [docker, multiarch]
  stage: build
  image:
    name: ghcr.io/claytonsingh/ubuntu-golang:riscv64
    docker:
      platform: linux/riscv64
  script:
    - flags="-X 'main.versionString=$(git show -s --format=%cs) ${CI_COMMIT_TAG} $(git rev-parse HEAD)'"
    - CGO_ENABLED=1 GOOS=linux GOARCH=riscv64 go build -o bin/icmp-exporter-riscv64 -ldflags="${flags}" ./cmd/icmp-exporter/
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week
