default:
  image: ubuntu:jammy

variables:
  GIT_DEPTH: 1

# Define Stages
stages:
  - build

build-amd64:
  tags: [docker]
  stage: build
  script:
    - apt update && apt install -y ca-certificates golang-go build-essential
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o bin/prom-icmp-amd64 src/*.go
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-arm64:
  tags: [docker]
  stage: build
  script:
    - apt update && apt install -y ca-certificates golang-go build-essential gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o bin/prom-icmp-arm64 src/*.go
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week

build-arm32:
  tags: [docker]
  stage: build
  script:
    - apt update && apt install -y ca-certificates golang-go build-essential gcc-arm-linux-gnueabi binutils-arm-linux-gnueabi
    - CGO_ENABLED=1 GOOS=linux GOARCH=arm CC=arm-linux-gnueabi-gcc go build -o bin/prom-icmp-arm32 src/*.go
  artifacts:
    paths:
      - bin/*
    expire_in: 1 week
    