on:
  push:
    tags: 'v*'

jobs:
  release-create:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set Env
      run: |
        echo "RELEASE_NAME=${GITHUB_REF_NAME} / $(git show -s --format=%cs)" >> ${GITHUB_ENV}
    - name: Create Release
      run: gh release create "${GITHUB_REF_NAME}" --title "${{ env.RELEASE_NAME }}" --generate-notes --draft
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
  release-matrix:
    name: Release Go Binary
    needs: [release-create]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - { goos: "linux", goarch: "amd64",   arch: "x64",     platform: "linux/amd64",   image: "golang:bullseye" }
          - { goos: "linux", goarch: "386",     arch: "x86",     platform: "linux/386",     image: "i386/golang:bullseye" }
          - { goos: "linux", goarch: "arm64",   arch: "arm64v8", platform: "linux/arm64",   image: "arm64v8/golang:bullseye" }
          - { goos: "linux", goarch: "arm",     arch: "arm32v7", platform: "linux/arm/v7",  image: "arm32v7/golang:bullseye" }
          - { goos: "linux", goarch: "arm",     arch: "arm32v5", platform: "linux/arm/v5",  image: "arm32v5/golang:bullseye" }
          - { goos: "linux", goarch: "riscv64", arch: "riscv64", platform: "linux/riscv64", image: "ghcr.io/claytonsingh/ubuntu-riscv-golang:latest" }
    steps:
    - uses: actions/checkout@v4
    - name: Set Env
      run: |
        echo "PACKAGE_NAME=icmp-exporter-${{ matrix.goos }}-${{ matrix.arch }}" >> ${GITHUB_ENV}
        echo "VERSION_STRING=$(git show -s --format=%cs) ${GITHUB_REF_NAME} ${GITHUB_SHA}" >> ${GITHUB_ENV}
    - uses: docker/setup-qemu-action@v3
    - name: Build Release
      run: |
        docker run --rm \
        --platform=${{ matrix.platform }} \
        -v $(pwd):/go/src -w /go/src \
        -e PACKAGE_NAME="${{ env.PACKAGE_NAME }}" \
        -e FLAGS="-X 'main.versionString=${{ env.VERSION_STRING }}'" \
        -e CGO_ENABLED=1 \
        -e GOOS=${{ matrix.goos }} \
        -e GOARCH=${{ matrix.goarch }} \
        -e GOFLAGS="-buildvcs=false" \
        ${{ matrix.image }} \
        .github/build.sh
    - name: Upload Release
      run: gh release upload "${GITHUB_REF_NAME}" "${{ env.PACKAGE_NAME }}.tar.gz"
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
